/* The following code was generated by JFlex 1.6.1 */

package python;

import static python.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/Faculdade Carlos 27-03-2020/3º Semestre/POO - Java/WorkSpace/AnalisadorLéxico/src/python/Python.flex</tt>
 */
class Python {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\4\1\60\1\60\1\3\22\0\1\5\1\24\1\31"+
    "\1\7\1\0\1\13\1\0\1\10\1\25\1\26\1\11\1\12\1\32"+
    "\1\12\1\30\1\12\12\2\1\27\1\0\1\22\1\23\1\22\2\0"+
    "\5\1\1\51\7\1\1\57\5\1\1\52\6\1\1\33\1\0\1\34"+
    "\1\0\1\1\1\0\1\14\1\53\1\47\1\16\1\37\1\36\1\56"+
    "\1\43\1\35\1\1\1\54\1\40\1\55\1\15\1\17\1\50\1\1"+
    "\1\20\1\41\1\21\1\44\1\1\1\42\1\46\1\45\1\1\12\0"+
    "\1\60\u1fa2\0\1\60\1\60\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\4\1\6"+
    "\1\7\1\1\2\10\6\2\1\11\1\12\1\1\1\13"+
    "\1\14\1\15\1\1\1\16\1\17\13\2\1\20\2\0"+
    "\1\21\1\12\1\2\1\22\2\2\1\23\2\2\1\11"+
    "\1\0\1\21\1\22\15\2\2\21\15\2\2\0\1\21"+
    "\7\2\1\0\1\21\4\2\1\0\2\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\61\0\61\0\304\0\61"+
    "\0\365\0\u0126\0\u0157\0\61\0\u0188\0\u01b9\0\u01ea\0\u021b"+
    "\0\u024c\0\u027d\0\u02ae\0\u02ae\0\u02ae\0\61\0\61\0\61"+
    "\0\u02df\0\61\0\61\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c"+
    "\0\u058d\0\u05be\0\61\0\u05ef\0\u0620\0\u0651\0\u0682\0\142"+
    "\0\u06b3\0\u06e4\0\61\0\u02df\0\u02df\0\142\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce"+
    "\0\u08ff\0\u0930\0\u0961\0\u058d\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0992\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04"+
    "\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c"+
    "\0\u0ebd\0\u0eee\0\u0f1f\0\u0e2a\0\u0f1f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\2\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\2"+
    "\1\31\1\5\1\32\1\33\1\34\1\35\1\36\2\3"+
    "\1\37\4\3\1\40\1\3\1\41\1\42\1\43\2\3"+
    "\1\44\1\45\63\0\1\3\1\46\11\0\6\3\13\0"+
    "\23\3\3\0\1\4\25\0\1\47\35\0\1\50\53\0"+
    "\4\11\1\0\54\11\4\51\1\0\3\51\1\52\21\51"+
    "\1\0\26\51\23\0\1\53\36\0\1\3\1\46\11\0"+
    "\1\3\1\54\4\3\13\0\4\3\1\55\16\3\2\0"+
    "\1\3\1\46\11\0\3\3\1\56\2\3\13\0\23\3"+
    "\2\0\1\3\1\46\11\0\6\3\13\0\2\3\1\57"+
    "\20\3\2\0\1\3\1\46\11\0\4\3\1\60\1\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\6\3\13\0"+
    "\2\3\1\61\20\3\2\0\1\3\1\46\11\0\4\3"+
    "\1\62\1\3\13\0\23\3\24\0\1\63\35\0\4\64"+
    "\1\0\24\64\1\65\1\0\26\64\1\0\1\3\1\46"+
    "\11\0\1\3\1\66\4\3\13\0\1\3\1\66\2\3"+
    "\1\66\13\3\1\67\2\3\2\0\1\3\1\46\11\0"+
    "\3\3\1\70\1\71\1\3\13\0\23\3\2\0\1\3"+
    "\1\46\11\0\6\3\13\0\3\3\1\72\5\3\1\73"+
    "\11\3\2\0\1\3\1\46\11\0\6\3\13\0\6\3"+
    "\1\74\14\3\2\0\1\3\1\46\11\0\3\3\1\75"+
    "\2\3\13\0\3\3\1\76\17\3\2\0\1\3\1\46"+
    "\11\0\1\77\5\3\13\0\23\3\2\0\1\3\1\46"+
    "\11\0\4\3\1\100\1\3\13\0\23\3\2\0\1\3"+
    "\1\46\11\0\4\3\1\101\1\3\13\0\23\3\2\0"+
    "\1\3\1\46\11\0\6\3\13\0\3\3\1\102\17\3"+
    "\2\0\1\3\1\46\11\0\3\3\1\103\2\3\13\0"+
    "\23\3\3\0\1\46\60\0\1\47\63\0\1\10\53\0"+
    "\4\51\1\0\3\51\1\104\21\51\1\0\32\51\1\0"+
    "\3\51\1\105\21\51\1\0\26\51\1\0\1\3\1\46"+
    "\11\0\2\3\1\60\3\3\13\0\23\3\2\0\1\3"+
    "\1\46\11\0\6\3\13\0\4\3\1\106\16\3\2\0"+
    "\1\3\1\46\11\0\5\3\1\60\13\0\23\3\2\0"+
    "\1\3\1\46\11\0\6\3\13\0\1\3\1\66\1\3"+
    "\1\66\17\3\2\0\1\3\1\46\11\0\5\3\1\107"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\6\3\13\0"+
    "\10\3\1\66\12\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\13\3\1\110\7\3\2\0\1\3\1\46\11\0"+
    "\4\3\1\66\1\3\13\0\23\3\2\0\1\3\1\46"+
    "\11\0\3\3\1\111\2\3\13\0\23\3\2\0\1\3"+
    "\1\46\11\0\6\3\13\0\1\112\3\3\1\113\16\3"+
    "\2\0\1\3\1\46\11\0\6\3\13\0\12\3\1\114"+
    "\10\3\2\0\1\3\1\46\11\0\6\3\13\0\1\115"+
    "\22\3\2\0\1\3\1\46\11\0\1\3\1\116\4\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\1\117\5\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\6\3\13\0"+
    "\3\3\1\120\17\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\7\3\1\113\13\3\2\0\1\3\1\46\11\0"+
    "\6\3\13\0\2\3\1\121\20\3\2\0\1\3\1\46"+
    "\11\0\3\3\1\122\2\3\13\0\23\3\2\0\1\3"+
    "\1\46\11\0\1\3\1\113\4\3\13\0\23\3\1\0"+
    "\4\123\1\124\3\123\1\125\1\51\20\123\1\124\26\123"+
    "\1\0\1\3\1\46\11\0\6\3\13\0\2\3\1\126"+
    "\20\3\2\0\1\3\1\46\11\0\6\3\13\0\7\3"+
    "\1\127\13\3\2\0\1\3\1\46\11\0\3\3\1\126"+
    "\2\3\13\0\23\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\20\3\1\66\2\3\2\0\1\3\1\46\11\0"+
    "\6\3\13\0\1\3\1\66\21\3\2\0\1\3\1\46"+
    "\11\0\6\3\13\0\2\3\1\66\20\3\2\0\1\3"+
    "\1\46\11\0\6\3\13\0\2\3\1\130\20\3\2\0"+
    "\1\3\1\46\11\0\6\3\13\0\3\3\1\113\17\3"+
    "\2\0\1\3\1\46\11\0\5\3\1\131\13\0\23\3"+
    "\2\0\1\3\1\46\11\0\6\3\13\0\4\3\1\132"+
    "\16\3\2\0\1\3\1\46\11\0\6\3\13\0\4\3"+
    "\1\113\16\3\2\0\1\3\1\46\11\0\1\133\5\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\6\3\13\0"+
    "\16\3\1\134\4\3\1\0\10\124\1\135\1\0\47\124"+
    "\4\123\1\124\3\123\1\136\1\51\20\123\1\124\26\123"+
    "\1\0\1\3\1\46\11\0\4\3\1\137\1\3\13\0"+
    "\23\3\2\0\1\3\1\46\11\0\4\3\1\140\1\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\6\3\13\0"+
    "\13\3\1\137\7\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\1\141\22\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\4\3\1\66\16\3\2\0\1\3\1\46\11\0"+
    "\6\3\13\0\17\3\1\66\3\3\2\0\1\3\1\46"+
    "\11\0\1\142\5\3\13\0\23\3\1\0\10\124\1\143"+
    "\1\0\47\124\4\123\1\124\3\123\1\144\21\123\1\124"+
    "\26\123\1\0\1\3\1\46\11\0\5\3\1\66\13\0"+
    "\23\3\2\0\1\3\1\46\11\0\1\3\1\66\4\3"+
    "\13\0\23\3\2\0\1\3\1\46\11\0\1\3\1\100"+
    "\4\3\13\0\23\3\2\0\1\3\1\46\11\0\6\3"+
    "\13\0\3\3\1\66\17\3\1\0\10\124\1\145\50\124";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3920];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\2\11\1\1\1\11\3\1\1\11"+
    "\11\1\3\11\1\1\2\11\14\1\2\0\1\1\1\11"+
    "\7\1\1\11\1\0\36\1\2\0\10\1\1\0\5\1"+
    "\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Python(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 182) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 21: break;
          case 2: 
            { lexeme = yytext(); return IDENTIFICADOR;
            }
          case 22: break;
          case 3: 
            { lexeme = yytext(); return NUMERO_INTEIRO;
            }
          case 23: break;
          case 4: 
            { /*Ignore*/
            }
          case 24: break;
          case 5: 
            { lexeme = yytext(); return QUEBRA_LINHA;
            }
          case 25: break;
          case 6: 
            { lexeme = yytext(); return IDENTACAO;
            }
          case 26: break;
          case 7: 
            { lexeme = yytext(); return COMENTARIO_SIMPLES;
            }
          case 27: break;
          case 8: 
            { lexeme = yytext(); return OPERADOR_ARITMETICO;
            }
          case 28: break;
          case 9: 
            { lexeme = yytext(); return OPERADOR_RELACIONAL;
            }
          case 29: break;
          case 10: 
            { lexeme = yytext(); return OPERADOR_ATRIBUICAO;
            }
          case 30: break;
          case 11: 
            { lexeme = yytext(); return DELIMITADOR_ABERTO;
            }
          case 31: break;
          case 12: 
            { lexeme = yytext(); return DELIMITADOR_FECHADO;
            }
          case 32: break;
          case 13: 
            { lexeme = yytext(); return FACA;
            }
          case 33: break;
          case 14: 
            { lexeme = yytext(); return LISTA_ABERTA;
            }
          case 34: break;
          case 15: 
            { lexeme = yytext(); return LISTA_FECHADA;
            }
          case 35: break;
          case 16: 
            { lexeme = yytext(); return NUMERO_FLUTUANTE;
            }
          case 36: break;
          case 17: 
            { lexeme = yytext(); return STRING;
            }
          case 37: break;
          case 18: 
            { lexeme = yytext(); return PALAVRA_RESERVADA;
            }
          case 38: break;
          case 19: 
            { lexeme = yytext(); return OPERADOR_LOGICO;
            }
          case 39: break;
          case 20: 
            { lexeme = yytext(); return COMENTARIO_MULTILINHAS;
            }
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
