package python;

public enum Token {

	QUEBRA_LINHA,OPERADOR_ARITMETICO,OPERADOR_LOGICO,OPERADOR_RELACIONAL,ERROR,NUMERO_INTEIRO,
	FACA,DELIMITADOR_FECHADO,PALAVRA_RESERVADA,DELIMITADOR_ABERTO,OPERADOR_ATRIBUICAO,COMENTARIO_MULTILINHAS,
	COMENTARIO_SIMPLES,IDENTACAO,NUMERO_FLUTUANTE,IDENTIFICADOR,STRING,LISTA_ABERTA,LISTA_FECHADA
	
}
